
stages:
  - validate
  - build
  - plan
  - deploy

variables:
  AWS_DEFAULT_REGION: "ap-south-1"
  AWS_REGION: "ap-south-1"
  PROJECT_NAME: "react-bluegreen"
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  BLUE_IMAGE_TAG: "latest"
  TF_STATE_BUCKET: "react-bluegreen-shared-tf-state"
  TF_LOCK_TABLE: "react-bluegreen-shared-tf-lock"
validate_frontend:
  stage: validate
  image: node:22-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build

build_and_push_image:
  stage: build
  image: ubuntu:24.04
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - apt-get update && apt-get install -y docker.io curl unzip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -q awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws
    - aws --version
    - aws ecr describe-repositories --repository-names "$ECR_REPOSITORY_NAME" --region "$AWS_REGION" >/dev/null 2>&1 || aws ecr create-repository --repository-name "$ECR_REPOSITORY_NAME" --image-scanning-configuration scanOnPush=true --region "$AWS_REGION" >/dev/null
    - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  script:
    - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$CI_COMMIT_SHORT_SHA"
    - echo "GREEN_IMAGE_TAG=$CI_COMMIT_SHORT_SHA" > deploy.env
    - docker build -t "$IMAGE_URI" .
    - docker push "$IMAGE_URI"
  artifacts:
    reports:
      dotenv: deploy.env


terraform_validate:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: ["/bin/sh", "-c"]
  stage: validate
  only:
    - master
    - main
    - tags
  before_script:
    - cd infra/envs/prod
    - terraform --version
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=prod/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
  script:
    - terraform validate

terraform_plan_green:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: ["/bin/sh", "-c"]
  stage: plan
  needs:
    - build_and_push_image
    - terraform_validate
  only:
    - master
    - main
    - tags
  dependencies:
    - build_and_push_image
  before_script:
    - cd infra/envs/prod
    - terraform --version
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=prod/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
  script:
    - terraform plan -var="aws_region=$AWS_REGION" -var="project_name=$PROJECT_NAME" -var="environment=prod" -var="active_color=blue" -var="blue_desired_capacity=1" -var="green_desired_capacity=1" -var="blue_image_tag=$BLUE_IMAGE_TAG" -var="green_image_tag=$GREEN_IMAGE_TAG" -out="planfile_green"
  artifacts:
    paths:
      - infra/envs/prod/planfile_green

terraform_apply_green:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  needs:
    - terraform_plan_green
  only:
    - master
    - main
    - tags
  dependencies:
    - terraform_plan_green
  before_script:
    - cd infra/envs/prod
    - terraform --version
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=prod/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
  script:
    - terraform apply -lock=true -auto-approve planfile_green
  when: manual

terraform_switch_to_green:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  needs:
    - terraform_apply_green
  only:
    - master
    - main
    - tags
  before_script:
    - cd infra/envs/prod
    - terraform --version
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=prod/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
  script:
    - terraform apply -lock=true -auto-approve -var="aws_region=$AWS_REGION" -var="project_name=$PROJECT_NAME" -var="environment=prod" -var="active_color=green" -var="blue_desired_capacity=1" -var="green_desired_capacity=1" -var="blue_image_tag=$BLUE_IMAGE_TAG" -var="green_image_tag=$GREEN_IMAGE_TAG"
  when: manual

terraform_decommission_blue:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  needs:
    - terraform_switch_to_green
  only:
    - master
    - main
    - tags
  before_script:
    - cd infra/envs/prod
    - terraform --version
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=prod/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
  script:
    - terraform apply -lock=true -auto-approve -var="aws_region=$AWS_REGION" -var="project_name=$PROJECT_NAME" -var="environment=prod" -var="active_color=green" -var="blue_desired_capacity=0" -var="green_desired_capacity=1" -var="blue_image_tag=$BLUE_IMAGE_TAG" -var="green_image_tag=$GREEN_IMAGE_TAG"
  when: manual

terraform_rollback_to_blue:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  needs:
    - terraform_switch_to_green
  only:
    - master
    - main
    - tags
  before_script:
    - cd infra/envs/prod
    - terraform --version
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=prod/terraform.tfstate" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_LOCK_TABLE" -backend-config="encrypt=true"
  script:
    - terraform apply -lock=true -auto-approve -var="aws_region=$AWS_REGION" -var="project_name=$PROJECT_NAME" -var="environment=prod" -var="active_color=blue" -var="blue_desired_capacity=1" -var="green_desired_capacity=1" -var="blue_image_tag=$BLUE_IMAGE_TAG" -var="green_image_tag=$GREEN_IMAGE_TAG"
  when: manual
